### ISSUE TITLE
Function fails for example matrix

### ISSUE THREAD

**Issue by jrwrigh** [jewettaij/jacobi#1]
If given the matrix:
```
[1, 2, 3]
[2, 5, 6]
[3, 6, 9]
```
`Diagonalize` will return the eigen values: ` 0.0, 0.699265, 14.300735`, when they should be `13.0, 0, 0`.

I'm not sure why the code is failing on this matrix specifically, as this matrix meets all the criteria for a Jacobi eigensolver (square, symmetric, dense). 

The issue appears to be an issue with the application of the rotation matrix for this problem. I've compared against a [python implementation](https://github.com/mateuv/MetodosNumericos/blob/master/python/NumericalMethodsInEngineeringWithPython/jacobi.py) of the Jacobi method (in addition to numpys `np.linalg.eig`). The values for cos(θ), sin(θ), and tan(θ) are the same on the first rotation ( `0.8112421851755608 0.584710284663765 0.7207592200561265`, respectively) , but the outcome of the rotation is different. The python code gets:
```
[ 1,  0,  3],
[ 2,  0,  0],
[ 3,  6, 13]
```

while this code gets:
```
[1.000000, -0.131646, 3.603147]
[2.000000, 0.675445, 0.000000]
[0.000000, 0.000000, 13.324555]
```
(ignoring the lower triangular portion obviously).

For running this C++ code, I simply added:
```c++
  double sym_mat[3][3] = {
  {1, 2, 3},
  {2, 5, 6},
  {3, 6, 9} };
  double eigvals[3], eigvecs[3][3];
  const int NF = 3;
        int n = 3;

  Jacobi<double,
         double*,
         double (*)[NF],
         double const (*)[NF]> ecalc(n);


  ecalc.Diagonalize(sym_mat,
                    eigvals,
                    eigvecs,
                    Jacobi<double,
                            double*,
                            double (*)[NF],
                            double const (*)[NF]>::DO_NOT_SORT);

  // TestJacobi(n_size, n_matr, emin, emax, n_tests, n_degeneracy, seed, eps);

  printf("\n");
  printf("eigvals: [ %f, %f, %f]\n", eigvals[0], eigvals[1], eigvals[2]);
  printf("eigvecs: [[%f, %f, %f]\n[%f, %f, %f]\n[%f, %f, %f]]\n", eigvecs[0][0], eigvecs[0][1], eigvecs[0][2], eigvecs[1][0], eigvecs[1][1], eigvecs[1][2], eigvecs[2][0], eigvecs[2][1], eigvecs[2][2]);
```
to the end of `test_jacobi.cpp:main`. I was able to reproduce the results when manually translating the C++ to C as well (which was my intended application to begin with).

**Comment by jrwrigh** [comment]
Closed. Embarrassingly, the issue was that the numpy array was stored as `int64`. I'm quite used to python just auto converting `int`s to floating point when necessary, so the thought of it being integer arthimetic didn't come to mind until I stepped through the python code one line at a time.

**Comment by jewettaij** [comment]
Hi James
   Thank you for reporting your findings even if they were mistaken.  And
thank you also for following up to let me know you fixed the problem.  My
software would be terrible if nobody reported issues, and it takes effort
to do that.

Cheers

Andrew
(I don't check GitHub anywhere near as often as I used to, but I haven't
abandoned jacobi_pd.)
